image: gitlab.kwant-project.org:5005/qt/adaptive:latest

stages:
  - prebuild
  - test

build docker:
  stage: prebuild
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - export CI_REF=${CI_COMMIT_TAG:-latest}
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_REF
  only:
    changes:
      - Dockerfile
      - environment.yml
      - test-requirements.txt

cache:
  paths:
    - .pip


stages:
  - test
  - deploy


before_script:
  - mkdir -p .pip
  - pip install asv scikit-optimize
  - pip install -r test-requirements.txt
  - asv machine --config=benchmarks/asv.conf.json --yes


test:
  stage: test
  script:
    - py.test --verbose --cov=adaptive --cov-report term --cov-report html adaptive
  artifacts:
    paths:
      - htmlcov


authors check:
  stage: test
  script:
    - MISSING_AUTHORS=$(git shortlog -s HEAD | sed -e "s/^[0-9\t ]*//"| xargs -i sh -c 'grep -q "{}" AUTHORS.md || echo "{} missing from authors"')
    - if [ ! -z "$MISSING_AUTHORS" ]; then { echo $MISSING_AUTHORS; exit 1; }; fi
  allow_failure: true


check whitespace style:
  stage: test
  script: ./check_whitespace
  allow_failure: true


benchmarks for master:
  stage: test
  script:
    - asv run --config=benchmarks/asv.conf.json --skip-existing-commits ALL
  artifacts:
    paths:
      - benchmarks/results
      - benchmarks/env
    expire_in: 7d
  only:
    - master


benchmarks not master:
  stage: test
  script:
    - asv run --config=benchmarks/asv.conf.json master..${CI_COMMIT_REF_NAME}
  except:
    - master


upload benchmarks:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && ssh-keyscan tnw-tn1.tudelft.net >> ~/.ssh/known_hosts
    - echo $WEBSITE_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  script:
    - asv publish
    - "rsync -ravz --delete benchmarks/html/* adaptive-asv@tnw-tn1.tudelft.net:"
  after_script:
    - rm -rf ~/.ssh
