name: nox

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set Python version for nox
      run: echo "PY_VERSION=$(echo ${version})" >> $GITHUB_ENV
      shell: bash
      env:
        version: ${{ matrix.python-version }}
    - name: Register Python problem matcher
      run: echo "::add-matcher::.github/workflows/matchers/pytest.json"
    - name: Install dependencies
      run: pip install nox pytest-github-actions-annotate-failures
    - name: Test with nox using minimal dependencies
      run: nox -e "pytest-${{ env.PY_VERSION }}(all_deps=False)"
    - name: Test with nox with all dependencies
      run: nox -e "pytest-${{ env.PY_VERSION }}(all_deps=True)"
