name: nox

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Register Python problem matcher
      run: echo "::add-matcher::.github/workflows/matchers/pytest.json"
    - name: Install dependencies
      run: pip install nox pytest-github-actions-annotate-failures
    - name: Test with nox using minimal dependencies
      run: nox -e "pytest-${{ matrix.python-version }}(all_deps=False)"
    - name: Test with nox with all dependencies
      run: nox -e "pytest-${{ matrix.python-version }}(all_deps=True)"
