name: tox

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set Python version for tox
      run: echo "PY_VERSION=$(echo py${version//./})" >> $GITHUB_ENV
      shell: bash
      env:
        version: ${{ matrix.python-version }}
    - name: Register Python problem matcher
      run: echo "::add-matcher::.github/workflows/matchers/pytest.json"
    - name: Install dependencies
      run: pip install tox pytest-github-actions-annotate-failures
    - name: Test with tox using minimal dependencies
      run: tox -e ${{ env.PY_VERSION }}-mindeps
    - name: Clean
      run: tox -e clean
    - name: Test with tox with all dependencies
      run: tox -e ${{ env.PY_VERSION }}-alldeps
